config/routes.rb
Rails.application.routes.draw do

  resources :events

  get 'welcome/index'
  get 'welcome/discover'
  get 'welcome/connect'
  get 'welcome/sell'
  get 'welcome/mytickets'

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order(:date)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create

    @event = Event.new
    @event.hometeam = params[:event][:hometeam]
    @event.visitor = params[:event][:visitor]
    @event.date = params[:event][:date]


    if @event.save

      flash[:notice] = "Event was saved successfully."
      redirect_to @event
    else

      flash.now[:alert] = "There was an error saving the event. Please try again."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.hometeam = params[:event][:hometeam]
    @event.visitor = params[:event][:visitor]
    @event.date = params[:event][:date]


    if @event.save
      flash[:notice] = "Event was updated successfully."
      redirect_to @event
    else
      flash.now[:alert] = "There was an error saving the event. Please try again."
      render :edit
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def discover
  end

  def sell
  end

  def connect
  end

  def mytickets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for @event do |f| %>
  <%= f.label :home_team, "Home Team" %><br />
  <%= f.text_field :hometeam %>
  <br />
  <%= f.label :opponent, "Opponent" %><br />
  <%= f.text_field :visitor %>
  <br />
  <%= f.label :Date %><br />
  <%= f.datetime_select :date %>



  <br />
  <%= f.submit "Save" %>
<% end %>

app/views/events/index.html.erb
<div class="events-container">
<% @events.each do |event| %>
<div class="event">
  <div class="event-date">
    <div class="day"><%= event.date.strftime("%a") %></div>
    <div class="month-day"><%= event.date.strftime("%b") %> <%= event.date.strftime("%d") %></div>
  </div>
  <div class="event-info">
    <%= link_to event do %>
      <div><%= event.visitor%> at <%= event.hometeam%></div>
      <div><%= event.date.strftime("%l:%M %p") %></div>
    <% end %>
  </div>
  <div class="event-price">
    <div class="from">from</div>
    <div class="price">$10</div>
  </div>
</div>
<% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event do |f| %>
  <%= f.label :home_team, "Home Team" %><br />
  <%= f.text_field :hometeam %>
  <br />

  <%= f.label :opponent, "Opponent" %><br />
  <%= f.text_field :visitor %>
  <br />

  <%= f.label :date, "Date" %><br />
  <%= f.text_field :date %>

  <br />
  <%= f.submit "Save" %>
<% end %>

app/views/events/show.html.erb
<%= link_to "Edit", edit_event_path(@event) %>

<h1><%= @event.tickets.count %> ticket(s) available!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stubhub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul>
    <li><%= link_to "Gametime", root_path %></li>    
    <li><%= link_to "Discover", welcome_discover_path %></li>
    <li><%= link_to "Sell",  welcome_sell_path %></li>
    <li><%= link_to "Connect",  welcome_connect_path %></li>
    <li><%= link_to "My Tickets",  welcome_mytickets_path %></li>
  </ul>

<%= yield %>

</body>
</html>

app/views/welcome/connect.html.erb
<h1>Connect!<h1>

app/views/welcome/discover.html.erb
<h1>Events!<h1>

app/views/welcome/index.html.erb
<h1>LAST MINUTE TICKETS</h1>
<h3>The seats you want, at the price you want, right now.</h3>

app/views/welcome/index0.html.erb
<h1>LAST MINUTE TICKETS</h1>
<h3>The seats you want, at the price you want, right now.</h3>

app/views/welcome/mytickets.html.erb
<h1>My Tickets!<h1>

app/views/welcome/sell.html.erb
<h1>Sell!<h1>